### ISSUE TITLE
Possible security vulnerability 👮‍♂️🚨

### ISSUE THREAD

**Issue by Dawiducik** [lukaszmojek/PackagesOfFuture#21]
# !!!CREDENTIALS LEAK!!!
## Dear maintainers!
Recently, when I was looking through the repository, I came across possible credentials leak on the line:
https://github.com/lukaszmojek/PackagesOfFuture/blob/0c6e821b2fc2ea12c8da7fefeaf419e5e1d4a6c4/Console.ApiSandbox/Program.cs#L16

Could you please take over it and fix it ASAP?
Thanks in advance to your security department and pen-testers.

**Comment by lukaszmojek** [comment]
Oh, good catch @Dawiducik! I'm glad, that I have such meticulous followers as you.
However this user never existed, and I have only written that part, to show my colleague, how he could send requests to the API.
Nontheless, thanks for your time and take care!
